# Mishap type definitions for the Paradox 5E starship mishap actors.
# DRAFT content, written to match the format of John's 24 reference actors
# (Fire / Explosion / Listing / Pitch and Roll / Wind Shear). Placeholders:
#   {N}=actor name, {DC}=save DC, {D}=damage dice (e.g. 3d6), {R}=work radius ft,
#   {H}=HP regained, {CD}=countdown, {T}=tier word for "a second <tier> <type>"
# Each spec:
#   key: exact component mishap name(s) this actor type answers to
#   name: display base name
#   dmg: damage type, save: save ability, skill: the mishap's contested skill
#   fix: checks a crew member uses to Correct it
#   obvious: True = doesn't need Diagnosis
#   hp: "high" (20/45/70/95/120) or "mid" (20/35/55/75/95)
#   primary: ability the mishap is strongest in
#   a1/a2: signature actions (name, text); r1: reaction on a failed Correct (name, text)
#   spread: reaction/escalation trigger (name, text)
#   trait: contested-Correct flavour name; fuel: (name, text) what makes it worse
#   next_alt: alternate mishap type on Completion
#   m/c/x: extra features gained at Major / Critical / Catastrophic: (kind, name, text), kind action|reaction|trait
#   icon: core Foundry icon

SPECS = [
 dict(key=["Weapon-Break"], name="Weapon Break", dmg="piercing", save="dex", skill="ath", primary="str",
      fix="Technology Toolkit or Engineering", obvious=True, hp="mid",
      a1=("Seized Mechanism", "The weapon system at {N}'s station can't be fired until the start of the next round."),
      a2=("Stripped Linkage", "Choose another weapon on the same arc. Until {N} is Corrected, attacks with that weapon have disadvantage."),
      r1=("Recoil Snap", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] piercing damage from flying parts on a failed save, or half as much damage on a successful one."),
      spread=("Chain Failure", "When the ship fires any weapon while {N} is active, roll a d20. On 11 or higher, {N} regains {H} hit points."),
      trait=("Jammed Tight", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Strained Hardpoint", "Whenever {N} would take thunder or force damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Explosion",
      m=("action", "Barrel Fracture", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] piercing damage on a failed save, or half as much on a success."),
      c=("reaction", "Cascading Breakdown", "When a creature succeeds on a Correct action against {N}, {N} loses no hit points unless that creature also succeeds on a DC {DC} Strength (Athletics) check."),
      x=("action", "Mount Tears Free", "The weapon mount is torn from the hull. The ship takes [[/r {D}]] bludgeoning damage and gains a Minor Explosion mishap within the work radius."),
      icon="icons/weapons/guns/gun-pistol-flintlock-metal.webp"),
 dict(key=["Operator-Injury"], name="Operator Injury", dmg="lightning", save="con", skill="ath", primary="con",
      fix="Medicine", obvious=True, hp="mid",
      a1=("Pinned at the Console", "One creature crewing the affected station is restrained until the start of the next round."),
      a2=("Feedback Spike", "The creature crewing the affected station must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] lightning damage."),
      r1=("Painful Jolt", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] lightning damage on a failed save, or half as much damage on a successful one."),
      spread=("Station Unmanned", "While {N} is active, the affected station's actions cost 1 more Tempo."),
      trait=("Stubborn Wound", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Live Current", "Whenever {N} would take lightning damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Crew-Injury",
      m=("action", "Arc Across the Deck", "Each creature within the work radius must succeed on a DC {DC} Dexterity saving throw or take [[/r {D}]] lightning damage."),
      c=("reaction", "Shock Lock", "When a creature within the work radius takes damage from {N}, that creature can't take reactions until the start of its next turn."),
      x=("action", "Console Overload", "The affected station is offline until {N} is Corrected."),
      icon="icons/skills/wounds/injury-body-pain-gray.webp"),
 dict(key=["Crew-Injury"], name="Crew Injury", dmg="bludgeoning", save="con", skill="ath", primary="con",
      fix="Medicine", obvious=True, hp="mid",
      a1=("Casualties", "One creature within the work radius gains one level of Exhaustion unless it succeeds on a DC {DC} Constitution saving throw."),
      a2=("Panic", "Each creature within the work radius must succeed on a DC {DC} Wisdom saving throw or be frightened until the start of the next round."),
      r1=("Aggravated Wound", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Hands Short", "While {N} is active, Gain Tempo checks made on the ship have a −1 penalty."),
      trait=("Hard Triage", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Collapsing Bulkheads", "Whenever {N} would take bludgeoning or thunder damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Loss-of-Control",
      m=("action", "Crush", "Each creature within the work radius must make a DC {DC} Strength saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much on a success."),
      c=("reaction", "Shock", "When a creature within the work radius drops to 0 hit points, {N} regains {H} hit points."),
      x=("action", "Mass Casualty", "Every station except the Commander's has disadvantage on its next check."),
      icon="icons/skills/wounds/injury-stitched-flesh-red.webp"),
 dict(key=["Loss-of-Control"], name="Loss of Control", dmg="bludgeoning", save="str", skill="acr", primary="dex",
      fix="Piloting or Acrobatics", obvious=True, hp="mid",
      a1=("Uncommanded Turn", "The ship turns 1 facing in a direction chosen by the GM."),
      a2=("Unresponsive Helm", "The Helmsman's next Maneuver costs 1 more Tempo."),
      r1=("Thrown Across the Bridge", "When a creature fails a Correct action, that creature must make a DC {DC} Strength saving throw, taking [[/r {D}]] bludgeoning damage and falling prone on a failed save, or half as much damage on a successful one."),
      spread=("Drift", "At the end of each round while {N} is active, the ship moves 1 range band in the direction it is facing."),
      trait=("Fighting the Controls", "the creature makes the check contested by {N}'s Acrobatics."),
      fuel=("Momentum", "Whenever the ship moves 2 or more range bands in one round, {N} regains {H} hit points."),
      next_alt="Loss-of-Speed",
      m=("action", "Spin", "The ship turns 2 facings in a direction chosen by the GM."),
      c=("reaction", "Overcorrection", "When the ship takes damage over its Damage Threshold, {N} gains 1 countdown counter back."),
      x=("action", "Tumble", "The ship turns 180°. Each creature aboard must succeed on a DC {DC} Strength saving throw or fall prone."),
      icon="icons/tools/navigation/compass-plain-blue.webp"),
 dict(key=["Jam"], name="Jam", dmg="bludgeoning", save="dex", skill="ath", primary="str",
      fix="Technology Toolkit or Athletics", obvious=True, hp="mid",
      a1=("Feed Stoppage", "The weapon system at {N}'s station can't be fired until the start of the next round."),
      a2=("Seized Breech", "The next attack made with the jammed weapon has disadvantage."),
      r1=("Snapback", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Fouled Feed", "When the jammed weapon is fired, {N} regains {H} hit points."),
      trait=("Stuck Fast", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Heat Warp", "Whenever {N} would take fire damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Weapon-Break",
      m=("action", "Double Feed", "A second weapon on the same arc can't be fired until the start of the next round."),
      c=("reaction", "Cook-Off", "When a creature fails a Correct action by 5 or more, the ship gains a Minor Explosion mishap within the work radius."),
      x=("action", "Welded Solid", "The jammed weapon is offline until {N} is Corrected."),
      icon="icons/tools/smithing/hammer-sledge-steel-grey.webp"),
 dict(key=["Misfire"], name="Misfire", dmg="force", save="dex", skill="acr", primary="dex",
      fix="Technology Toolkit or Perception", obvious=True, hp="mid",
      a1=("Stray Shot", "The weapon at {N}'s station fires at a random target within range, friend or foe."),
      a2=("Hangfire", "The next attack with the affected weapon is delayed: it resolves at the end of the round instead of on the Gunner's turn."),
      r1=("Discharge", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] force damage on a failed save, or half as much damage on a successful one."),
      spread=("Charge Bleed", "When the affected weapon is fired, roll a d20. On 11 or higher, the shot misses automatically and {N} regains {H} hit points."),
      trait=("Erratic Timing", "the creature makes the check contested by {N}'s Acrobatics."),
      fuel=("Overcharged Capacitors", "Whenever {N} would take force or lightning damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Explosion",
      m=("action", "Backblast", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] force damage on a failed save, or half as much on a success."),
      c=("reaction", "Chain Misfire", "When the Gunner uses Aimed Shot or Empowered Shot, {N} regains {H} hit points."),
      x=("action", "Friendly Fire", "The affected weapon fires at the ship itself: the ship takes damage as if hit by that weapon."),
      icon="icons/skills/targeting/crosshair-pointed-orange.webp"),
 dict(key=["Loss-of-Speed"], name="Loss of Speed", dmg="cold", save="con", skill="ath", primary="con",
      fix="Engineering or Technology Toolkit", obvious=True, hp="mid",
      a1=("Thrust Drop", "The ship's Speed is reduced by 1 until the start of the next round (minimum 1)."),
      a2=("Sputter", "The Helmsman can't use Maneuver until the start of the next round."),
      r1=("Coolant Spray", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] cold damage on a failed save, or half as much damage on a successful one."),
      spread=("Dead in Space", "While {N} is active, the ship can't Flee."),
      trait=("Stubborn Drive", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Frozen Lines", "Whenever {N} would take cold damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Loss-of-Power",
      m=("action", "Stall", "The ship's Speed is reduced by 2 until the start of the next round (minimum 1)."),
      c=("reaction", "Drag", "When the Engineer uses Reroute Power on Propulsion, {N} regains {H} hit points instead of the Speed being gained."),
      x=("action", "Engine Seizure", "The Propulsion system gains a second Mishap token (offline) until {N} is Corrected."),
      icon="icons/magic/control/buff-flight-wings-runes-blue.webp"),
 dict(key=["Backlash"], name="Backlash", dmg="force", save="con", skill="ath", primary="con",
      fix="Arcana or Engineering", obvious=True, hp="mid",
      a1=("Reflected Surge", "The creature crewing the affected station must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] force damage."),
      a2=("Power Kick", "The next action taken at the affected station costs 1 more Tempo."),
      r1=("Rebound", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] force damage on a failed save, or half as much damage on a successful one."),
      spread=("Feedback Loop", "Whenever any station spends 3 or more Tempo on one action, {N} regains {H} hit points."),
      trait=("Recoiling Energy", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Absorbs Force", "Whenever {N} would take force damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Explosion",
      m=("action", "Surge Wave", "Each creature within the work radius must make a DC {DC} Constitution saving throw, taking [[/r {D}]] force damage on a failed save, or half as much on a success."),
      c=("reaction", "Amplified Return", "When a creature within the work radius deals damage to {N}, that creature takes half the damage as force damage."),
      x=("action", "Grid Blowback", "Every station takes a −2 penalty to its next check as the power grid bucks."),
      icon="icons/magic/lightning/bolt-strike-blue.webp"),
 dict(key=["Swivel-Lock"], name="Swivel Lock", dmg="bludgeoning", save="str", skill="ath", primary="str",
      fix="Technology Toolkit or Athletics", obvious=True, hp="mid",
      a1=("Frozen Traverse", "The weapon at {N}'s station can fire only into the arc it currently faces until the start of the next round."),
      a2=("Grinding Gears", "Attacks with the affected weapon have disadvantage until the start of the next round."),
      r1=("Wrenched Arm", "When a creature fails a Correct action, that creature must make a DC {DC} Strength saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Seized Bearing", "When the ship turns 2 or more facings in one round, {N} regains {H} hit points."),
      trait=("Locked Bearing", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Cold Weld", "Whenever {N} would take cold damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Weapon-Break",
      m=("action", "Wrong Arc", "The weapon mount slews to the opposite arc and can't be moved until the start of the next round."),
      c=("reaction", "Stripped Ring", "When a creature succeeds on a Correct action against {N}, the weapon still can't change arcs until the end of the next round."),
      x=("action", "Mount Seizure", "The affected weapon is offline until {N} is Corrected."),
      icon="icons/tools/hand/wrench-steel-grey.webp"),
 dict(key=["Wild-Magic"], name="Wild-Magic", dmg="force", save="wis", skill="arc", primary="cha",
      fix="Arcana", obvious=False, hp="mid",
      a1=("Surge", "Roll on the Wild Magic Surge table (or the GM chooses an effect) centered on {N}."),
      a2=("Unstable Weave", "Until the start of the next round, any spell cast within the work radius requires a DC {DC} Arcana check or fails."),
      r1=("Arcane Recoil", "When a creature fails a Correct action, that creature must make a DC {DC} Wisdom saving throw, taking [[/r {D}]] force damage on a failed save, or half as much damage on a successful one."),
      spread=("Resonance", "When a spell is cast aboard the ship while {N} is active, {N} regains {H} hit points."),
      trait=("Shifting Pattern", "the creature makes the check contested by {N}'s Arcana."),
      fuel=("Feeds on Magic", "Whenever {N} would take force or radiant damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Psychic-Blast",
      m=("action", "Reality Hiccup", "One creature within the work radius is teleported to an unoccupied space within 30 feet chosen by the GM."),
      c=("reaction", "Spell Drain", "When a creature within the work radius casts a spell, {N} regains hit points equal to twice the spell's level."),
      x=("action", "Arcane Storm", "Each creature within the work radius must make a DC {DC} Wisdom saving throw, taking [[/r {D}]] force damage on a failed save, or half as much on a success."),
      icon="icons/magic/symbols/runes-star-pentagon-magenta.webp"),
 dict(key=["Wild Magic"], name="Wild Magic", dmg="force", save="wis", skill="arc", primary="cha",
      fix="Arcana", obvious=False, hp="mid",
      a1=("Ward Flicker", "The ship's shields flicker. Divert Power to Shields can't be used until the start of the next round."),
      a2=("Warped Ward", "The next attack against the ship ignores its shield component's AC bonus."),
      r1=("Ward Recoil", "When a creature fails a Correct action, that creature must make a DC {DC} Wisdom saving throw, taking [[/r {D}]] force damage on a failed save, or half as much damage on a successful one."),
      spread=("Hungry Ward", "When the ship is hit by a magical attack while {N} is active, {N} regains {H} hit points."),
      trait=("Shifting Ward", "the creature makes the check contested by {N}'s Arcana."),
      fuel=("Feeds on Magic", "Whenever {N} would take force or radiant damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Vulnerability",
      m=("action", "Inverted Ward", "Until the start of the next round, attacks against the ship have advantage."),
      c=("reaction", "Ward Lash", "When a creature succeeds on a Correct action against {N}, it takes [[/r {D}]] force damage."),
      x=("action", "Ward Collapse", "The Shields system gains a Mishap token until {N} is Corrected."),
      icon="icons/magic/defensive/shield-barrier-flaming-diamond-teal.webp"),
 dict(key=["Loss-of-Power"], name="Loss of Power", dmg="lightning", save="con", skill="ath", primary="con",
      fix="Engineering or Technology Toolkit", obvious=False, hp="mid",
      a1=("Brownout", "One station chosen by the GM can't take actions that cost Tempo until the start of the next round."),
      a2=("Dimming", "The bridge lights fail; the area within the work radius is dim light until the start of the next round."),
      r1=("Arc Flash", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] lightning damage on a failed save, or half as much damage on a successful one."),
      spread=("Load Shedding", "When the Engineer uses Reroute Power, {N} regains {H} hit points."),
      trait=("Tracing the Fault", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Short Circuit", "Whenever {N} would take lightning damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Electrical",
      m=("action", "Rolling Blackout", "Two stations chosen by the GM can't take actions that cost Tempo until the start of the next round."),
      c=("reaction", "Capacitor Drain", "When any station Gains Tempo, {N} regains {H} hit points."),
      x=("action", "Total Blackout", "The Power System gains a Mishap token until {N} is Corrected."),
      icon="icons/magic/lightning/bolt-forked-large-blue.webp"),
 dict(key=["Fuel-Depletion"], name="Fuel Depletion", dmg="poison", save="con", skill="ath", primary="con",
      fix="Engineering or Investigation", obvious=False, hp="mid",
      a1=("Starved Feed", "The ship's Speed is reduced by 1 until the start of the next round (minimum 1)."),
      a2=("Fumes", "The area within the work radius is lightly obscured and each creature there must succeed on a DC {DC} Constitution saving throw or be poisoned until the start of the next round."),
      r1=("Fuel Spray", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] poison damage on a failed save, or half as much damage on a successful one."),
      spread=("Burning Reserves", "When the ship moves 2 or more range bands in one round, {N} regains {H} hit points."),
      trait=("Hunting the Leak", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Volatile Vapors", "Whenever {N} would take fire damage, the ship gains a Minor Fire mishap within the work radius."),
      next_alt="Loss-of-Speed",
      m=("action", "Dry Tanks", "The Helmsman can't use Maneuver until the start of the next round."),
      c=("reaction", "Vapor Lock", "When a creature succeeds on a Correct action against {N}, roll a d20. On 10 or lower, the ship gains a Minor Fire mishap."),
      x=("action", "Flameout", "The Propulsion system gains a Mishap token until {N} is Corrected."),
      icon="icons/consumables/potions/potion-tube-corked-green.webp"),
 dict(key=["Psychic-Blast"], name="Psychic Blast", dmg="psychic", save="wis", skill="ins", primary="cha",
      fix="Insight or Arcana", obvious=True, hp="mid",
      a1=("Mind Spike", "One creature within the work radius must succeed on a DC {DC} Wisdom saving throw or be stunned until the end of its next turn."),
      a2=("Whispers", "Each creature within the work radius has disadvantage on Intelligence and Wisdom checks until the start of the next round."),
      r1=("Psychic Backwash", "When a creature fails a Correct action, that creature must make a DC {DC} Wisdom saving throw, taking [[/r {D}]] psychic damage on a failed save, or half as much damage on a successful one."),
      spread=("Echoing Minds", "When a creature within the work radius fails a Wisdom saving throw, {N} regains {H} hit points."),
      trait=("Mental Static", "the creature makes the check contested by {N}'s Insight."),
      fuel=("Feeds on Fear", "Whenever a creature within the work radius becomes frightened, {N} regains {H} hit points."),
      next_alt="Wild-Magic",
      m=("action", "Terror Wave", "Each creature within the work radius must succeed on a DC {DC} Wisdom saving throw or be frightened until the start of the next round."),
      c=("reaction", "Mind Lash", "When a creature within the work radius casts a spell, that creature takes [[/r {D}]] psychic damage."),
      x=("action", "Psychic Storm", "Each creature within the work radius must make a DC {DC} Wisdom saving throw, taking [[/r {D}]] psychic damage on a failed save, or half as much on a success."),
      icon="icons/magic/perception/eye-ringed-glow-angry-small-teal.webp"),
 dict(key=["Gravity-Spike"], name="Gravity Spike", dmg="bludgeoning", save="str", skill="ath", primary="str",
      fix="Engineering or Athletics", obvious=True, hp="high",
      a1=("Heavy Deck", "The area within the work radius is difficult terrain and creatures there have disadvantage on Dexterity checks until the start of the next round."),
      a2=("Crushing Weight", "One creature within the work radius must succeed on a DC {DC} Strength saving throw or fall prone and be restrained until the start of the next round."),
      r1=("Slammed Down", "When a creature fails a Correct action, that creature must make a DC {DC} Strength saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Gravity Well", "At the end of each round, unsecured objects within the work radius are pulled 5 feet toward {N}."),
      trait=("Crushing Field", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Mass Feedback", "Whenever {N} would take force damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Gravity-Loss",
      m=("action", "Pressure Crush", "Each creature within the work radius must make a DC {DC} Strength saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much on a success."),
      c=("reaction", "Pinning Surge", "When a creature within the work radius stands up from prone, it must succeed on a DC {DC} Strength saving throw or fall prone again."),
      x=("action", "Hull Stress", "The ship takes [[/r {D}]] bludgeoning damage as its frame buckles."),
      icon="icons/magic/earth/orb-stone-smoke-teal.webp"),
 dict(key=["Gravity-Loss"], name="Gravity Loss", dmg="bludgeoning", save="dex", skill="acr", primary="dex",
      fix="Engineering or Acrobatics", obvious=True, hp="high",
      a1=("Float Free", "Creatures within the work radius that aren't secured drift 10 feet in a direction chosen by the GM."),
      a2=("Loose Objects", "Unsecured objects within the work radius drift; the area is difficult terrain until the start of the next round."),
      r1=("Tumble", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] bludgeoning damage from a collision on a failed save, or half as much damage on a successful one."),
      spread=("Weightless Drift", "While {N} is active, creatures without a fly speed have disadvantage on Strength (Athletics) checks aboard the ship."),
      trait=("No Leverage", "the creature makes the check contested by {N}'s Acrobatics."),
      fuel=("Field Collapse", "Whenever {N} would take force damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Gravity-Spike",
      m=("action", "Debris Storm", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much on a success."),
      c=("reaction", "Snap Return", "When a creature succeeds on a Correct action against {N}, gravity returns suddenly: each creature within the work radius falls prone unless it succeeds on a DC {DC} Dexterity saving throw."),
      x=("action", "Spin Out", "Every station loses its next reaction as the crew is thrown loose."),
      icon="icons/magic/air/wind-vortex-swirl-blue.webp"),
 dict(key=["Electrical"], name="Electrical", dmg="lightning", save="dex", skill="acr", primary="dex",
      fix="Technology Toolkit or Engineering", obvious=False, hp="high",
      a1=("Live Wire", "One creature within the work radius must succeed on a DC {DC} Dexterity saving throw or take [[/r {D}]] lightning damage."),
      a2=("Sparks", "The area within the work radius is lightly obscured by sparks and smoke until the start of the next round."),
      r1=("Shock", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] lightning damage on a failed save, or half as much damage on a successful one."),
      spread=("Short to Ground", "When a creature wearing metal armor enters the work radius, {N} regains {H} hit points."),
      trait=("Hidden Short", "the creature makes the check contested by {N}'s Acrobatics."),
      fuel=("Fed by Current", "Whenever {N} would take lightning damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Fire",
      m=("action", "Arcing Discharge", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] lightning damage on a failed save, or half as much on a success."),
      c=("reaction", "Chain Arc", "When a creature within the work radius takes lightning damage, one other creature within 10 feet of it takes half that damage."),
      x=("action", "Panel Fire", "The ship gains a Fire mishap within the work radius."),
      icon="icons/magic/lightning/bolt-strike-blue.webp"),
 dict(key=["Founder"], name="Founder", dmg="cold", save="con", skill="ath", primary="con",
      fix="Engineering or Athletics", obvious=True, hp="high",
      a1=("Hull Breach", "The area within the work radius is exposed to vacuum: creatures there must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] cold damage and begin suffocating."),
      a2=("Venting", "Unsecured creatures and objects within the work radius are pulled 10 feet toward {N}."),
      r1=("Decompression", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] cold damage on a failed save, or half as much damage on a successful one."),
      spread=("Losing Atmosphere", "While {N} is active, the ship's Mishap Threshold is reduced by 2 for determining new Mishaps."),
      trait=("Sealing the Breach", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Widening Crack", "Whenever the ship takes damage over its Damage Threshold, {N} regains {H} hit points."),
      next_alt="Loss-of-Control",
      m=("action", "Explosive Decompression", "Each creature within the work radius must make a DC {DC} Strength saving throw or be pulled 20 feet toward {N} and take [[/r {D}]] bludgeoning damage."),
      c=("reaction", "Bulkhead Failure", "When a creature succeeds on a Correct action against {N}, roll a d20. On 10 or lower, a second Minor Founder opens within 30 feet."),
      x=("action", "Breaking Up", "The ship takes [[/r {D}]] bludgeoning damage and the Hull system gains a Mishap token."),
      icon="icons/magic/water/wave-water-blue.webp"),
 dict(key=["Radiation"], name="Radiation", dmg="radiant", save="con", skill="ath", primary="con",
      fix="Medicine or Engineering", obvious=False, hp="high",
      a1=("Irradiate", "Each creature within the work radius must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] radiant damage."),
      a2=("Sickness", "One creature within the work radius must succeed on a DC {DC} Constitution saving throw or be poisoned until the end of its next long rest."),
      r1=("Exposure", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] radiant damage on a failed save, or half as much damage on a successful one."),
      spread=("Contamination", "The work radius grows by 5 feet at the end of each round while {N} is active (maximum double its starting radius)."),
      trait=("Invisible Hazard", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Fed by Energy", "Whenever {N} would take radiant or fire damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Core-Overload",
      m=("action", "Hot Zone", "The work radius becomes difficult terrain as the crew moves carefully; creatures ending their turn there take [[/r {D}]] radiant damage."),
      c=("reaction", "Lingering Dose", "When a creature leaves the work radius, it must succeed on a DC {DC} Constitution saving throw or gain one level of Exhaustion."),
      x=("action", "Containment Failure", "Every creature aboard must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] radiant damage."),
      icon="icons/magic/light/explosion-star-glow-yellow.webp"),
 dict(key=["Core-Overload"], name="Core Overload", dmg="fire", save="con", skill="ath", primary="con",
      fix="Engineering or Arcana", obvious=True, hp="high",
      a1=("Heat Spike", "Each creature within the work radius must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] fire damage."),
      a2=("Runaway Output", "The next action taken at the Engineer's station costs 1 more Tempo."),
      r1=("Scald", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] fire damage on a failed save, or half as much damage on a successful one."),
      spread=("Critical Mass", "When the Engineer uses Reroute Power, {N} regains {H} hit points."),
      trait=("Unstable Core", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Fed by Energy", "Whenever {N} would take fire or radiant damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Explosion",
      m=("action", "Coolant Boil", "The area within the work radius is heavily obscured by steam until the start of the next round."),
      c=("reaction", "Radiation Leak", "When a creature fails a Correct action by 5 or more, the ship gains a Minor Radiation mishap within the work radius."),
      x=("action", "Meltdown Warning", "The Power System gains a Mishap token until {N} is Corrected."),
      icon="icons/magic/fire/explosion-embers-evade-silhouette.webp"),
 dict(key=["Defect"], name="Defect", dmg="bludgeoning", save="dex", skill="dec", primary="int",
      fix="Investigation or Technology Toolkit", obvious=False, hp="mid",
      a1=("Latent Flaw", "The ship's Armor Class is reduced by 1 until the start of the next round."),
      a2=("Rattle", "The Navigator has disadvantage on their next check."),
      r1=("Panel Blowout", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Stress Fracture", "When the ship is hit by an attack while {N} is active, {N} regains {H} hit points."),
      trait=("Hard to Find", "the creature makes the check contested by {N}'s Deception."),
      fuel=("Fatigue", "Whenever {N} would take thunder damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Vulnerability",
      m=("action", "Plate Shear", "The ship's Armor Class is reduced by 2 until the start of the next round."),
      c=("reaction", "Hidden Crack", "When a creature succeeds on a Correct action against {N}, the GM rolls a d20. On 10 or lower, {N} isn't actually fixed; it regains {H} hit points."),
      x=("action", "Structural Failure", "The Armor system gains a Mishap token until {N} is Corrected."),
      icon="icons/equipment/shield/heater-steel-worn.webp"),
 dict(key=["Fuel-Issue"], name="Fuel Issue", dmg="poison", save="con", skill="ath", primary="con",
      fix="Engineering or Investigation", obvious=False, hp="mid",
      a1=("Contaminated Feed", "The Power System station has disadvantage on its next check."),
      a2=("Toxic Fumes", "Each creature within the work radius must succeed on a DC {DC} Constitution saving throw or be poisoned until the start of the next round."),
      r1=("Fuel Splash", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] poison damage on a failed save, or half as much damage on a successful one."),
      spread=("Sludge", "When the Engineer uses Vent, {N} regains {H} hit points."),
      trait=("Hidden Contaminant", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Volatile", "Whenever {N} would take fire damage, the ship gains a Minor Fire mishap within the work radius."),
      next_alt="Fuel-Depletion",
      m=("action", "Clogged Lines", "The ship's Speed is reduced by 1 until the start of the next round (minimum 1)."),
      c=("reaction", "Flash Point", "When a creature fails a Correct action by 5 or more, the ship gains a Minor Fire mishap within the work radius."),
      x=("action", "Engine Choke", "The Propulsion system gains a Mishap token until {N} is Corrected."),
      icon="icons/consumables/potions/bottle-round-corked-green.webp"),
 dict(key=["Overpower"], name="Overpower", dmg="lightning", save="con", skill="ath", primary="con",
      fix="Engineering or Technology Toolkit", obvious=True, hp="high",
      a1=("Surge", "One system chosen by the GM is impaired (as if it had one Mishap token) until the start of the next round."),
      a2=("Overheat", "The creature crewing the Engineer station must succeed on a DC {DC} Constitution saving throw or take [[/r {D}]] lightning damage."),
      r1=("Blown Relay", "When a creature fails a Correct action, that creature must make a DC {DC} Constitution saving throw, taking [[/r {D}]] lightning damage on a failed save, or half as much damage on a successful one."),
      spread=("Runaway Load", "Whenever any station Gains Tempo, {N} regains {H} hit points."),
      trait=("Live Bus", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Fed by Current", "Whenever {N} would take lightning damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Core-Overload",
      m=("action", "Fried Circuits", "The next Reroute Power costs 1 more Tempo."),
      c=("reaction", "Overflow", "When the Engineer uses Divert Power to Shields, {N} regains {H} hit points."),
      x=("action", "Blown Grid", "The Power System gains a Mishap token until {N} is Corrected."),
      icon="icons/magic/lightning/bolt-forked-large-blue.webp"),
 dict(key=["Vulnerability"], name="Vulnerability", dmg="force", save="dex", skill="dec", primary="int",
      fix="Investigation or Arcana", obvious=False, hp="mid",
      a1=("Weak Point", "The next attack that hits the ship deals an extra [[/r {D}]] damage."),
      a2=("Exposed Seam", "Until the start of the next round, attacks against the ship from one arc chosen by the GM have advantage."),
      r1=("Seam Burst", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] force damage on a failed save, or half as much damage on a successful one."),
      spread=("Widening Gap", "When the ship takes damage over its Damage Threshold, {N} regains {H} hit points."),
      trait=("Subtle Flaw", "the creature makes the check contested by {N}'s Deception."),
      fuel=("Resonant Weakness", "Whenever {N} would take force damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Defect",
      m=("action", "Shield Gap", "Divert Power to Shields can't be used until the start of the next round."),
      c=("reaction", "Exploited", "When the ship is hit by a critical hit, {N} gains 1 countdown counter back."),
      x=("action", "Open Wound", "The ship's Damage Threshold is 0 until {N} is Corrected."),
      icon="icons/magic/defensive/shield-barrier-deflect-teal.webp"),
 dict(key=["Loss-of-Lift"], name="Loss of Lift", dmg="bludgeoning", save="dex", skill="acr", primary="dex",
      fix="Piloting or Engineering", obvious=True, hp="mid",
      a1=("Sink", "In an atmosphere, the ship loses altitude; creatures aboard must succeed on a DC {DC} Dexterity saving throw or fall prone."),
      a2=("Stall Warning", "The Helmsman has disadvantage on their next check."),
      r1=("Lurch", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] bludgeoning damage on a failed save, or half as much damage on a successful one."),
      spread=("Losing Altitude", "At the end of each round while {N} is active, the ship moves 1 range band closer to the ground (or the gravity well)."),
      trait=("Dead Air", "the creature makes the check contested by {N}'s Acrobatics."),
      fuel=("Downdraft", "Whenever the ship turns 2 or more facings in one round, {N} regains {H} hit points."),
      next_alt="Loss-of-Control",
      m=("action", "Dive", "The ship's Speed is reduced by 1 and it can't gain altitude until the start of the next round."),
      c=("reaction", "Freefall", "When a creature succeeds on a Correct action against {N}, each creature aboard falls prone unless it succeeds on a DC {DC} Dexterity saving throw."),
      x=("action", "Crash Course", "The ship takes [[/r {D}]] bludgeoning damage as it strikes terrain or debris."),
      icon="icons/magic/air/wind-vortex-swirl-blue.webp"),
 dict(key=["Rigging-Failure"], name="Rigging Failure", dmg="slashing", save="dex", skill="ath", primary="str",
      fix="Athletics or Technology Toolkit", obvious=True, hp="mid",
      a1=("Snapped Line", "One creature within the work radius must succeed on a DC {DC} Dexterity saving throw or take [[/r {D}]] slashing damage."),
      a2=("Tangle", "One creature within the work radius must succeed on a DC {DC} Strength saving throw or be restrained until the start of the next round."),
      r1=("Whiplash", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] slashing damage on a failed save, or half as much damage on a successful one."),
      spread=("Fraying", "When the ship turns 2 or more facings in one round, {N} regains {H} hit points."),
      trait=("Under Tension", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Wind Load", "Whenever {N} would take thunder damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Loss-of-Lift",
      m=("action", "Cable Storm", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] slashing damage on a failed save, or half as much on a success."),
      c=("reaction", "Cascade", "When a creature succeeds on a Correct action against {N}, roll a d20. On 10 or lower, a second Minor Rigging Failure starts within 30 feet."),
      x=("action", "Rig Collapse", "The Propulsion system gains a Mishap token until {N} is Corrected."),
      icon="icons/sundries/survival/rope-wrapped-brown.webp"),
 dict(key=["Break"], name="Break", dmg="piercing", save="dex", skill="ath", primary="str",
      fix="Engineering or Technology Toolkit", obvious=True, hp="mid",
      a1=("Cracked Housing", "The Power System station has disadvantage on its next check."),
      a2=("Shrapnel", "One creature within the work radius must succeed on a DC {DC} Dexterity saving throw or take [[/r {D}]] piercing damage."),
      r1=("Splinter", "When a creature fails a Correct action, that creature must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] piercing damage on a failed save, or half as much damage on a successful one."),
      spread=("Load Stress", "When the Engineer uses Reroute Power, {N} regains {H} hit points."),
      trait=("Fractured", "the creature makes the check contested by {N}'s Athletics."),
      fuel=("Brittle", "Whenever {N} would take thunder or cold damage, it instead regains a number of hit points equal to the damage dealt."),
      next_alt="Loss-of-Power",
      m=("action", "Split", "Each creature within the work radius must make a DC {DC} Dexterity saving throw, taking [[/r {D}]] piercing damage on a failed save, or half as much on a success."),
      c=("reaction", "Spreading Crack", "When the ship takes damage over its Damage Threshold, {N} gains 1 countdown counter back."),
      x=("action", "Shatter", "The Power System gains a Mishap token until {N} is Corrected."),
      icon="icons/tools/smithing/hammer-sledge-steel-grey.webp"),
]
